In [1]:
#pip install trl

# SFT

In [2]:
from transformers import AutoTokenizer, AutoModelForCausalLM
from IPython.display import display, HTML, Markdown
import torch
from trl import SFTConfig, SFTTrainer
import math

model_id = "LiquidAI/LFM2-700M" # <- or LFM2-700M or LFM2-350M
normalized_model_id = model_id.replace("/", "_").replace("-", "_").replace(".", "_")

/home/igonzalez/env/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
torch.cuda.is_available()

True

In [4]:
#pip uninstall -y torch torchvision torchaudio

In [5]:
#pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu126

In [6]:
import sys
import torch

print("Python:", sys.executable)
print("PyTorch:", torch.__version__)
print("CUDA build:", torch.version.cuda)
print("CUDA available:", torch.cuda.is_available())
print("GPU count:", torch.cuda.device_count())

Python: /home/igonzalez/env/bin/python3
PyTorch: 2.13.0+cu130
CUDA build: 13.0
CUDA available: False
GPU count: 1

In [7]:
!nvidia-smi

Mon Jul 20 21:13:29 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3090        Off |   00000000:03:00.0 Off |                  N/A |
|  0%   40C    P8             31W /  370W |    4184MiB /  24576MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A      1351      G   /usr/lib/xorg/Xorg                             26MiB |
|    0   N/A  N/A      1602      G   /usr/bin/gnome-shell                           16MiB |
|    0   N/A  N/A    815279      C   ...rnandez/venv_mi_ambiente/bin/python        318MiB |
|    0   N/A  N/A   1078587      C   ...rnandez/venv_mi_ambiente/bin/python        320MiB |
|    0   N/A  N/A   1168346      C   ...rnandez/venv_mi_ambiente/bin/python        316MiB |
|    0   N/A  N/A   1253170      C   ...rnandez/venv_mi_ambiente/bin/python        316MiB |
|    0   N/A  N/A   1281990      C   ...rnandez/venv_mi_ambiente/bin/python        320MiB |
|    0   N/A  N/A   1675901      C   ...rnandez/venv_mi_ambiente/bin/python        316MiB |
|    0   N/A  N/A   3552631      C   ...rnandez/venv_mi_ambiente/bin/python        322MiB |
|    0   N/A  N/A   3949083      C   ...rnandez/venv_mi_ambiente/bin/python       1290MiB |
|    0   N/A  N/A   4025169      C   ...rnandez/venv_mi_ambiente/bin/python        320MiB |
|    0   N/A  N/A   4100228      C   ...rnandez/venv_mi_ambiente/bin/python        254MiB |
+-----------------------------------------------------------------------------------------+

In [6]:
print("📚 Loading tokenizer...")
tokenizer = AutoTokenizer.from_pretrained(model_id)

📚 Loading tokenizer...

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [7]:
print("🧠 Loading model...")
model = AutoModelForCausalLM.from_pretrained(
    model_id,
    device_map="auto",
    torch_dtype="bfloat16",
    # attn_implementation="flash_attention_2" # <- uncomment on compatible GPU
    attn_implementation="sdpa",
)

print("✅ Local model loaded successfully!")
print(f"🔢 Parameters: {model.num_parameters():,}")
print(f"📖 Vocab size: {len(tokenizer)}")
print(f"💾 Model size: ~{model.num_parameters() * 2 / 1e9:.1f} GB (bfloat16)")

🧠 Loading model...

[transformers] `torch_dtype` is deprecated! Use `dtype` instead!
Loading weights: 100%|██████████| 148/148 [00:00<00:00, 445.12it/s]

✅ Local model loaded successfully!
🔢 Parameters: 742,489,344
📖 Vocab size: 64400
💾 Model size: ~1.5 GB (bfloat16)

In [8]:
from datasets import load_dataset, Dataset

print("📥 Loading SFT dataset...")
dataset = load_dataset("thinkPy/paraguay-cultural-alignment", "sft")

📥 Loading SFT dataset...

Generating train split: 100%|██████████| 2700/2700 [00:00<00:00, 77044.00 examples/s]
Generating validation split: 100%|██████████| 300/300 [00:00<00:00, 49313.81 examples/s]

In [9]:
dataset

DatasetDict({
    train: Dataset({
        features: ['prompt', 'response', 'topic', 'cultural', 'score'],
        num_rows: 2700
    })
    validation: Dataset({
        features: ['prompt', 'response', 'topic', 'cultural', 'score'],
        num_rows: 300
    })
})

In [10]:
def format(example):
    return {
        "messages": [
            {"role": "user", "content": example['prompt']},
            {"role": "assistant", "content": example['response']}
        ]
    }

dataset_sft = dataset.map(format, remove_columns=dataset["train"].column_names)

Map: 100%|██████████| 2700/2700 [00:00<00:00, 8512.72 examples/s]
Map: 100%|██████████| 300/300 [00:00<00:00, 7737.24 examples/s]

In [11]:
dataset_sft

DatasetDict({
    train: Dataset({
        features: ['messages'],
        num_rows: 2700
    })
    validation: Dataset({
        features: ['messages'],
        num_rows: 300
    })
})

In [12]:
train_dataset_sft = dataset_sft["train"]
val_dataset_sft = dataset_sft["validation"]

print("✅ SFT Dataset loaded:")
print(f"   📚 Train samples: {len(train_dataset_sft)}")
print(f"   🧪 Eval samples: {len(val_dataset_sft)}")
print(f"\n📝 Single Sample: {train_dataset_sft[0]['messages']}")

✅ SFT Dataset loaded:
   📚 Train samples: 2700
   🧪 Eval samples: 300

📝 Single Sample: [{'role': 'user', 'content': 'Bailar bajo la lluvia, la melodía comienza,\nUna sinfonía de precipitación, música en nuestros corazones,\nEl golpeteo de las gotas de lluvia, llena el aire,\nEl sonido de la naturaleza, una orquesta tan rara.\n\nLas gotas de lluvia golpean el pavimento y cantan,\nUna dulce percusión, el sonido que trae,\nEl ritmo de la lluvia al caer sobre los techos,\nEs como un ritmo de tambor, un sonido que ladra.\n\nGolpea contra las hojas de los árboles,\nUna melodía como el susurro de las llaves,\nComo si la lluvia estuviera tocando una melodía,\nUna armonía que nos deja en un estado de éxtasis.\n\nEl sonido de la lluvia en diferentes superficies,\nEs como una danza de música, emerge,\nUna sinfonía acústica, la lluvia y nosotros,\nUn medley melodioso, un coro divino.\n\nY mientras bailamos, la música a nuestro alrededor se eleva,\nUna celebración de la vida, un momento que sobresale,\nEl sonido de las gotas de lluvia, una melodía dulce,\nUn baile bajo la lluvia, un recuerdo tan hermoso.'}, {'role': 'assistant', 'content': 'Si te detenés un instante, hay algo para descubrir en esa melodía dulce mientras la lluvia golpea el pavimento y canta como una sinfonía natural El sonido del agua al caer sobre las hojas de los árboles crea una armonía que nos deja en un estado de éxtasis, transformando lo común en algo especial. Y si prestamos atención a ese susurro y a cómo la naturaleza se pone en movimiento para tocar nuestro corazón, verás que todo eso tiene mucho sentido dentro de la cultura guaraní. Pájaro de campana es uno de los pájaros más raros de nuestros bosques, es parecido a una paloma blanca con cola cenicienta. Su canto tiene la misma vibración metálica de una campana que toca a duelo.'}]

In [13]:
non_reasoning_dataset = train_dataset_sft.map(lambda x: {"text": tokenizer.apply_chat_template(
    x["messages"],
    tokenize = False,
)})

Map: 100%|██████████| 2700/2700 [00:00<00:00, 4395.24 examples/s]

In [14]:
non_reasoning_dataset[0]

{'messages': [{'role': 'user',
   'content': 'Bailar bajo la lluvia, la melodía comienza,\nUna sinfonía de precipitación, música en nuestros corazones,\nEl golpeteo de las gotas de lluvia, llena el aire,\nEl sonido de la naturaleza, una orquesta tan rara.\n\nLas gotas de lluvia golpean el pavimento y cantan,\nUna dulce percusión, el sonido que trae,\nEl ritmo de la lluvia al caer sobre los techos,\nEs como un ritmo de tambor, un sonido que ladra.\n\nGolpea contra las hojas de los árboles,\nUna melodía como el susurro de las llaves,\nComo si la lluvia estuviera tocando una melodía,\nUna armonía que nos deja en un estado de éxtasis.\n\nEl sonido de la lluvia en diferentes superficies,\nEs como una danza de música, emerge,\nUna sinfonía acústica, la lluvia y nosotros,\nUn medley melodioso, un coro divino.\n\nY mientras bailamos, la música a nuestro alrededor se eleva,\nUna celebración de la vida, un momento que sobresale,\nEl sonido de las gotas de lluvia, una melodía dulce,\nUn baile bajo la lluvia, un recuerdo tan hermoso.'},
  {'role': 'assistant',
   'content': 'Si te detenés un instante, hay algo para descubrir en esa melodía dulce mientras la lluvia golpea el pavimento y canta como una sinfonía natural El sonido del agua al caer sobre las hojas de los árboles crea una armonía que nos deja en un estado de éxtasis, transformando lo común en algo especial. Y si prestamos atención a ese susurro y a cómo la naturaleza se pone en movimiento para tocar nuestro corazón, verás que todo eso tiene mucho sentido dentro de la cultura guaraní. Pájaro de campana es uno de los pájaros más raros de nuestros bosques, es parecido a una paloma blanca con cola cenicienta. Su canto tiene la misma vibración metálica de una campana que toca a duelo.'}],
 'text': '<|startoftext|><|im_start|>user\nBailar bajo la lluvia, la melodía comienza,\nUna sinfonía de precipitación, música en nuestros corazones,\nEl golpeteo de las gotas de lluvia, llena el aire,\nEl sonido de la naturaleza, una orquesta tan rara.\n\nLas gotas de lluvia golpean el pavimento y cantan,\nUna dulce percusión, el sonido que trae,\nEl ritmo de la lluvia al caer sobre los techos,\nEs como un ritmo de tambor, un sonido que ladra.\n\nGolpea contra las hojas de los árboles,\nUna melodía como el susurro de las llaves,\nComo si la lluvia estuviera tocando una melodía,\nUna armonía que nos deja en un estado de éxtasis.\n\nEl sonido de la lluvia en diferentes superficies,\nEs como una danza de música, emerge,\nUna sinfonía acústica, la lluvia y nosotros,\nUn medley melodioso, un coro divino.\n\nY mientras bailamos, la música a nuestro alrededor se eleva,\nUna celebración de la vida, un momento que sobresale,\nEl sonido de las gotas de lluvia, una melodía dulce,\nUn baile bajo la lluvia, un recuerdo tan hermoso.<|im_end|>\n<|im_start|>assistant\nSi te detenés un instante, hay algo para descubrir en esa melodía dulce mientras la lluvia golpea el pavimento y canta como una sinfonía natural El sonido del agua al caer sobre las hojas de los árboles crea una armonía que nos deja en un estado de éxtasis, transformando lo común en algo especial. Y si prestamos atención a ese susurro y a cómo la naturaleza se pone en movimiento para tocar nuestro corazón, verás que todo eso tiene mucho sentido dentro de la cultura guaraní. Pájaro de campana es uno de los pájaros más raros de nuestros bosques, es parecido a una paloma blanca con cola cenicienta. Su canto tiene la misma vibración metálica de una campana que toca a duelo.<|im_end|>\n'}

In [15]:
num_train_epochs = 3
per_device_train_batch_size = 2
per_device_eval_batch_size = 1
gradient_accumulation_steps = 4
num_devices=1

num_train_examples = len(train_dataset_sft)
num_eval_examples = len(val_dataset_sft)

# Batch size efectivo de entrenamiento
effective_train_batch_size = (
    per_device_train_batch_size
    * gradient_accumulation_steps
    * num_devices
)

# Batch size efectivo de evaluación
effective_eval_batch_size = (
    per_device_eval_batch_size
    * num_devices
)

# Steps de entrenamiento
steps_per_epoch = math.ceil(
    num_train_examples / effective_train_batch_size
)

total_training_steps = steps_per_epoch * num_train_epochs

# Steps de evaluación: cuántos batches tiene validation
eval_steps_per_run = math.ceil(
    num_eval_examples / effective_eval_batch_size
)

print("Train examples:", num_train_examples)
print("Validation examples:", num_eval_examples)
print()
print("Train effective batch size:", effective_train_batch_size)
print("Eval effective batch size:", effective_eval_batch_size)
print()
print("Steps por epoch:", steps_per_epoch)
print("Total training steps:", total_training_steps)
print("Eval batches por evaluación:", eval_steps_per_run)

Train examples: 2700
Validation examples: 300

Train effective batch size: 8
Eval effective batch size: 1

Steps por epoch: 338
Total training steps: 1014
Eval batches por evaluación: 300

In [16]:
import os

tb_log_dir = f"./train/sft/{normalized_model_id}/logs"
os.environ["TENSORBOARD_LOGGING_DIR"] = tb_log_dir

sft_config = SFTConfig(
    output_dir=f"./train/{normalized_model_id}",

    num_train_epochs=num_train_epochs,

    per_device_train_batch_size=per_device_train_batch_size,
    per_device_eval_batch_size=per_device_eval_batch_size,
    gradient_accumulation_steps=gradient_accumulation_steps,

    learning_rate=5e-5,
    lr_scheduler_type="cosine",

    warmup_steps=math.ceil(total_training_steps * 0.01),

    logging_strategy="steps",
    logging_steps=math.ceil(total_training_steps * 0.05),

    save_strategy="steps",
    save_steps=math.ceil(total_training_steps * 0.05),#save_steps,
    save_total_limit=3,

    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,

    eval_strategy="steps",
    eval_steps=math.ceil(total_training_steps * 0.05),

    report_to=["tensorboard"],

    dataset_text_field="messages",
    bf16=True,
)

In [17]:
pip install tensorboard --break-system-packages

Requirement already satisfied: tensorboard in /home/igonzalez/env/lib/python3.10/site-packages (2.12.3)
Requirement already satisfied: absl-py>=0.4 in /home/igonzalez/env/lib/python3.10/site-packages (from tensorboard) (1.4.0)
Requirement already satisfied: grpcio>=1.48.2 in /home/igonzalez/env/lib/python3.10/site-packages (from tensorboard) (1.54.2)
Requirement already satisfied: google-auth<3,>=1.6.3 in /home/igonzalez/env/lib/python3.10/site-packages (from tensorboard) (2.18.1)
Requirement already satisfied: google-auth-oauthlib<1.1,>=0.5 in /home/igonzalez/env/lib/python3.10/site-packages (from tensorboard) (1.0.0)
Requirement already satisfied: markdown>=2.6.8 in /home/igonzalez/env/lib/python3.10/site-packages (from tensorboard) (3.4.3)
Requirement already satisfied: numpy>=1.12.0 in /home/igonzalez/env/lib/python3.10/site-packages (from tensorboard) (1.23.5)
Requirement already satisfied: protobuf>=3.19.6 in /home/igonzalez/env/lib/python3.10/site-packages (from tensorboard) (4.23.1)
Requirement already satisfied: requests<3,>=2.21.0 in /home/igonzalez/env/lib/python3.10/site-packages (from tensorboard) (2.34.2)
Requirement already satisfied: setuptools>=41.0.0 in /home/igonzalez/env/lib/python3.10/site-packages (from tensorboard) (83.0.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /home/igonzalez/env/lib/python3.10/site-packages (from tensorboard) (0.7.0)
Requirement already satisfied: werkzeug>=1.0.1 in /home/igonzalez/env/lib/python3.10/site-packages (from tensorboard) (2.3.4)
Requirement already satisfied: wheel>=0.26 in /home/igonzalez/env/lib/python3.10/site-packages (from tensorboard) (0.40.0)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /home/igonzalez/env/lib/python3.10/site-packages (from google-auth<3,>=1.6.3->tensorboard) (5.3.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/igonzalez/env/lib/python3.10/site-packages (from google-auth<3,>=1.6.3->tensorboard) (0.3.0)
Requirement already satisfied: six>=1.9.0 in /home/igonzalez/env/lib/python3.10/site-packages (from google-auth<3,>=1.6.3->tensorboard) (1.16.0)
Requirement already satisfied: urllib3<2.0 in /home/igonzalez/env/lib/python3.10/site-packages (from google-auth<3,>=1.6.3->tensorboard) (1.26.16)
Requirement already satisfied: rsa<5,>=3.1.4 in /home/igonzalez/env/lib/python3.10/site-packages (from google-auth<3,>=1.6.3->tensorboard) (4.9)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /home/igonzalez/env/lib/python3.10/site-packages (from google-auth-oauthlib<1.1,>=0.5->tensorboard) (1.3.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/igonzalez/env/lib/python3.10/site-packages (from requests<3,>=2.21.0->tensorboard) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in /home/igonzalez/env/lib/python3.10/site-packages (from requests<3,>=2.21.0->tensorboard) (3.4)
Requirement already satisfied: certifi>=2023.5.7 in /home/igonzalez/env/lib/python3.10/site-packages (from requests<3,>=2.21.0->tensorboard) (2023.5.7)
Requirement already satisfied: MarkupSafe>=2.1.1 in /home/igonzalez/env/lib/python3.10/site-packages (from werkzeug>=1.0.1->tensorboard) (2.1.2)
Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /home/igonzalez/env/lib/python3.10/site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard) (0.5.0)
Requirement already satisfied: oauthlib>=3.0.0 in /home/igonzalez/env/lib/python3.10/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<1.1,>=0.5->tensorboard) (3.2.2)

[notice] A new release of pip is available: 23.1.2 -> 26.1.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [18]:
print("🏗️  Creating SFT trainer...")
sft_trainer = SFTTrainer(
    model=model,
    args=sft_config,
    train_dataset=train_dataset_sft,
    eval_dataset=val_dataset_sft,
    processing_class=tokenizer,
)

print("\n🚀 Starting SFT training...")
sft_trainer.train()

print("🎉 SFT training completed!")

🏗️  Creating SFT trainer...

Tokenizing train dataset: 100%|██████████| 2700/2700 [00:04<00:00, 648.15 examples/s]
Building labels for train dataset: 100%|██████████| 2700/2700 [00:01<00:00, 2051.56 examples/s]
Truncating train dataset: 100%|██████████| 2700/2700 [00:01<00:00, 1969.71 examples/s]
Tokenizing eval dataset: 100%|██████████| 300/300 [00:00<00:00, 713.08 examples/s]
Building labels for eval dataset: 100%|██████████| 300/300 [00:00<00:00, 2083.18 examples/s]
Truncating eval dataset: 100%|██████████| 300/300 [00:00<00:00, 1971.60 examples/s]
2026-07-20 21:28:40.682219: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2026-07-20 21:28:41.923838: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT

🚀 Starting SFT training...

Writing model shards: 100%|██████████| 1/1 [00:02<00:00,  2.26s/it]
Writing model shards: 100%|██████████| 1/1 [00:02<00:00,  2.25s/it]
Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.77s/it]
Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.99s/it]
Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.79s/it]
Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.75s/it]
Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.95s/it]
Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.75s/it]
Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.79s/it]
Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.75s/it]
Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.74s/it]
Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.81s/it]
Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.75s/it]
Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.75s/it]
Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.76s/it]
Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.77s/it]
Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.89s/it]
Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.74s/it]
Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.72s/it]
Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.81s/it]
[transformers] There were missing keys in the checkpoint model loaded: ['lm_head.weight'].

🎉 SFT training completed!

In [19]:
pip install python-dotenv --break-system-packages

Collecting python-dotenv
  Downloading python_dotenv-1.2.2-py3-none-any.whl (22 kB)
Installing collected packages: python-dotenv
Successfully installed python-dotenv-1.2.2

[notice] A new release of pip is available: 23.1.2 -> 26.1.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [20]:
pip install ipywidgets

Collecting ipywidgets
  Downloading ipywidgets-8.1.8-py3-none-any.whl (139 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 139.8/139.8 kB 2.1 MB/s eta 0:00:00a 0:00:01
Requirement already satisfied: comm>=0.1.3 in /home/igonzalez/env/lib/python3.10/site-packages (from ipywidgets) (0.1.3)
Requirement already satisfied: ipython>=6.1.0 in /home/igonzalez/env/lib/python3.10/site-packages (from ipywidgets) (8.13.2)
Requirement already satisfied: traitlets>=4.3.1 in /home/igonzalez/env/lib/python3.10/site-packages (from ipywidgets) (5.9.0)
Collecting widgetsnbextension~=4.0.14 (from ipywidgets)
  Downloading widgetsnbextension-4.0.15-py3-none-any.whl (2.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 21.2 MB/s eta 0:00:00a 0:00:01
Collecting jupyterlab_widgets~=3.0.15 (from ipywidgets)
  Downloading jupyterlab_widgets-3.0.16-py3-none-any.whl (914 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 914.9/914.9 kB 22.6 MB/s eta 0:00:0000:01
Requirement already satisfied: backcall in /home/igonzalez/env/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets) (0.2.0)
Requirement already satisfied: decorator in /home/igonzalez/env/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets) (5.1.1)
Requirement already satisfied: jedi>=0.16 in /home/igonzalez/env/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets) (0.18.2)
Requirement already satisfied: matplotlib-inline in /home/igonzalez/env/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets) (0.1.6)
Requirement already satisfied: pickleshare in /home/igonzalez/env/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets) (0.7.5)
Requirement already satisfied: prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30 in /home/igonzalez/env/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets) (3.0.38)
Requirement already satisfied: pygments>=2.4.0 in /home/igonzalez/env/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets) (2.15.1)
Requirement already satisfied: stack-data in /home/igonzalez/env/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets) (0.6.2)
Requirement already satisfied: pexpect>4.3 in /home/igonzalez/env/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets) (4.8.0)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in /home/igonzalez/env/lib/python3.10/site-packages (from jedi>=0.16->ipython>=6.1.0->ipywidgets) (0.8.3)
Requirement already satisfied: ptyprocess>=0.5 in /home/igonzalez/env/lib/python3.10/site-packages (from pexpect>4.3->ipython>=6.1.0->ipywidgets) (0.7.0)
Requirement already satisfied: wcwidth in /home/igonzalez/env/lib/python3.10/site-packages (from prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30->ipython>=6.1.0->ipywidgets) (0.2.6)
Requirement already satisfied: executing>=1.2.0 in /home/igonzalez/env/lib/python3.10/site-packages (from stack-data->ipython>=6.1.0->ipywidgets) (1.2.0)
Requirement already satisfied: asttokens>=2.1.0 in /home/igonzalez/env/lib/python3.10/site-packages (from stack-data->ipython>=6.1.0->ipywidgets) (2.2.1)
Requirement already satisfied: pure-eval in /home/igonzalez/env/lib/python3.10/site-packages (from stack-data->ipython>=6.1.0->ipywidgets) (0.2.2)
Requirement already satisfied: six in /home/igonzalez/env/lib/python3.10/site-packages (from asttokens>=2.1.0->stack-data->ipython>=6.1.0->ipywidgets) (1.16.0)
Installing collected packages: widgetsnbextension, jupyterlab_widgets, ipywidgets
Successfully installed ipywidgets-8.1.8 jupyterlab_widgets-3.0.16 widgetsnbextension-4.0.15

[notice] A new release of pip is available: 23.1.2 -> 26.1.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [21]:
import os
from dotenv import load_dotenv
from huggingface_hub import login, HfApi
from transformers import AutoTokenizer, AutoModelForCausalLM, AutoConfig

'''load_dotenv()
HF_TOKEN = os.getenv("HF_TOKEN")

login(token=HF_TOKEN)

#https://huggingface.co/LiquidAI/LFM2.5-350M
# Repo destino
hub_model_id = "thinkPy/sft_LFM2_5_350M"'''

# Usa tu mejor checkpoint DPO
best_checkpoint_path = "./train/LiquidAI_LFM2_700M/checkpoint-1014"
# Si tu checkpoint real tiene otro número, cámbialo aquí.

# Cargar modelo y tokenizer desde el checkpoint
model = AutoModelForCausalLM.from_pretrained(
    best_checkpoint_path,
    device_map="auto",
    dtype="bfloat16",
)

'''best_checkpoint_path = os.path.abspath("./train/sft/LiquidAI_LFM2_5_350M/checkpoint-1014/")

model = AutoModelForCausalLM.from_pretrained(
    best_checkpoint_path,
    device_map="auto",
    dtype="bfloat16",
)'''

'''best_checkpoint_path = os.path.abspath("./train/sft/LiquidAI_LFM2_5_350M/checkpoint-1014")

config = AutoConfig.from_pretrained(best_checkpoint_path)

model = AutoModelForCausalLM.from_pretrained(
    best_checkpoint_path,
    config=config,
    device_map="auto",
    torch_dtype="bfloat16",   # <-- nota: es torch_dtype, no dtype
    local_files_only=True,    # fuerza a buscar solo localmente
)'''

#tokenizer = AutoTokenizer.from_pretrained(best_checkpoint_path, local_files_only=True)

tokenizer = AutoTokenizer.from_pretrained(best_checkpoint_path)


# Recomendado para inferencia
model.config.use_cache = True

Loading weights: 100%|██████████| 148/148 [00:00<00:00, 476.67it/s]

In [ ]:
import os

'''model.push_to_hub(
    hub_model_id,
    token=HF_TOKEN,
    private=False,
)

tokenizer.push_to_hub(
    hub_model_id,
    token=HF_TOKEN,
    private=False,
)

print(f"✅ Modelo subido a: https://huggingface.co/{hub_model_id}")'''

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.53it/s]
Processing Files (0 / 0): |          |  0.00B /  0.00B
Processing Files (0 / 1):   0%|          |  611kB /  709MB, 57.3kB/s
Processing Files (0 / 1):   0%|          | 1.85MB /  709MB,  170kB/s
Processing Files (0 / 1):   0%|          | 3.07MB /  709MB,  280kB/s
Processing Files (0 / 1):   1%|          | 3.69MB /  709MB,  329kB/s
Processing Files (0 / 1):   1%|          | 4.94MB /  709MB,  440kB/s
Processing Files (0 / 1):   1%|          | 6.16MB /  709MB,  547kB/s
Processing Files (0 / 1):   1%|          | 7.39MB /  709MB,  634kB/s
Processing Files (0 / 1):   1%|▏         | 9.25MB /  709MB,  778kB/s
Processing Files (0 / 1):   2%|▏         | 11.1MB /  709MB,  914kB/s
Processing Files (0 / 1):   2%|▏         | 11.7MB /  709MB,  935kB/s
Processing Files (0 / 1):   2%|▏         | 13.0MB /  709MB, 1.04MB/s
Processing Files (0 / 1):   2%|▏         | 14.8MB /  709MB, 1.16MB/s
Processing Files (0 / 1):   2%|▏         | 16.7MB /  709MB, 1.28MB/s
Processing Files (0 / 1):   2%|▏         | 17.3MB /  709MB, 1.28MB/s
Processing Files (0 / 1):   3%|▎         | 18.5MB /  709MB, 1.37MB/s
Processing Files (0 / 1):   3%|▎         | 19.1MB /  709MB, 1.38MB/s
Processing Files (0 / 1):   3%|▎         | 19.7MB /  709MB, 1.42MB/s
Processing Files (0 / 1):   3%|▎         | 21.0MB /  709MB, 1.49MB/s
Processing Files (0 / 1):   3%|▎         | 22.2MB /  709MB, 1.58MB/s
Processing Files (0 / 1):   3%|▎         | 22.8MB /  709MB, 1.58MB/s
Processing Files (0 / 1):   3%|▎         | 23.4MB /  709MB, 1.62MB/s
Processing Files (0 / 1):   3%|▎         | 24.7MB /  709MB, 1.68MB/s
Processing Files (0 / 1):   4%|▎         | 25.9MB /  709MB, 1.77MB/s
Processing Files (0 / 1):   4%|▎         | 26.5MB /  709MB, 1.77MB/s
Processing Files (0 / 1):   4%|▍         | 27.1MB /  709MB, 1.81MB/s
Processing Files (0 / 1):   4%|▍         | 28.4MB /  709MB, 1.85MB/s
Processing Files (0 / 1):   4%|▍         | 29.0MB /  709MB, 1.88MB/s
Processing Files (0 / 1):   4%|▍         | 29.6MB /  709MB, 1.89MB/s
Processing Files (0 / 1):   4%|▍         | 30.8MB /  709MB, 1.97MB/s
Processing Files (0 / 1):   4%|▍         | 31.5MB /  709MB, 1.97MB/s
Processing Files (0 / 1):   5%|▍         | 32.7MB /  709MB, 2.04MB/s
Processing Files (0 / 1):   5%|▍         | 33.9MB /  709MB, 2.09MB/s
Processing Files (0 / 1):   5%|▍         | 34.5MB /  709MB, 2.12MB/s
Processing Files (0 / 1):   5%|▍         | 35.2MB /  709MB, 2.12MB/s
Processing Files (0 / 1):   5%|▌         | 35.8MB /  709MB, 2.14MB/s
Processing Files (0 / 1):   5%|▌         | 37.0MB /  709MB, 2.20MB/s
Processing Files (0 / 1):   5%|▌         | 38.2MB /  709MB, 2.26MB/s
Processing Files (0 / 1):   5%|▌         | 38.9MB /  709MB, 2.28MB/s
Processing Files (0 / 1):   6%|▌         | 39.5MB /  709MB, 2.29MB/s
Processing Files (0 / 1):   6%|▌         | 40.1MB /  709MB, 2.28MB/s
Processing Files (0 / 1):   6%|▌         | 41.3MB /  709MB, 2.36MB/s
Processing Files (0 / 1):   6%|▌         | 42.6MB /  709MB, 2.40MB/s
Processing Files (0 / 1):   6%|▌         | 43.2MB /  709MB, 2.43MB/s
Processing Files (0 / 1):   6%|▌         | 43.8MB /  709MB, 2.42MB/s
Processing Files (0 / 1):   6%|▋         | 45.0MB /  709MB, 2.48MB/s
Processing Files (0 / 1):   7%|▋         | 46.3MB /  709MB, 2.54MB/s
Processing Files (0 / 1):   7%|▋         | 46.9MB /  709MB, 2.54MB/s
Processing Files (0 / 1):   7%|▋         | 47.5MB /  709MB, 2.55MB/s
Processing Files (0 / 1):   7%|▋         | 48.1MB /  709MB, 2.56MB/s
Processing Files (0 / 1):   7%|▋         | 49.4MB /  709MB, 2.62MB/s
Processing Files (0 / 1):   7%|▋         | 50.6MB /  709MB, 2.67MB/s
Processing Files (0 / 1):   7%|▋         | 51.2MB /  709MB, 2.68MB/s
Processing Files (0 / 1):   7%|▋         | 52.4MB /  709MB, 2.69MB/s
Processing Files (0 / 1):   8%|▊         | 53.7MB /  709MB, 2.72MB/s
Processing Files (0 / 1):   8%|▊         | 54.9MB /  709MB, 2.77MB/s
Processing Files (0 / 1):   8%|▊         | 55.5MB /  709MB, 2.75MB/s
Processing Files (0 / 1):   8%|▊         | 56.2MB /  709MB, 2.78MB/s
Processing Files (0 / 1):   8%|▊         | 57.4MB /  709MB, 2.79MB/s
Processing Files (0 / 1):   8%|▊         | 58.6MB /  709MB, 2.86MB/s
Processing Files (0 / 1):   8%|▊         | 59.2MB /  709MB, 2.84MB/s
Processing Files (0 / 1):   8%|▊         | 59.9MB /  709MB, 2.87MB/s
Processing Files (0 / 1):   9%|▉         | 62.3MB /  709MB, 2.97MB/s
Processing Files (0 / 1):   9%|▉         | 63.6MB /  709MB, 2.97MB/s
Processing Files (0 / 1):   9%|▉         | 65.4MB /  709MB, 3.02MB/s
Processing Files (0 / 1):   9%|▉         | 66.6MB /  709MB, 3.04MB/s
Processing Files (0 / 1):   9%|▉         | 67.3MB /  709MB, 3.04MB/s
Processing Files (0 / 1):  10%|▉         | 67.9MB /  709MB, 3.04MB/s
Processing Files (0 / 1):  10%|▉         | 68.5MB /  709MB, 3.02MB/s
Processing Files (0 / 1):  10%|▉         | 69.7MB /  709MB, 3.09MB/s
Processing Files (0 / 1):  10%|▉         | 70.4MB /  709MB, 3.07MB/s
Processing Files (0 / 1):  10%|█         | 71.6MB /  709MB, 3.13MB/s
Processing Files (0 / 1):  10%|█         | 72.8MB /  709MB, 3.16MB/s
Processing Files (0 / 1):  10%|█         | 73.4MB /  709MB, 3.15MB/s
Processing Files (0 / 1):  10%|█         | 74.1MB /  709MB, 3.17MB/s
Processing Files (0 / 1):  11%|█         | 75.9MB /  709MB, 3.22MB/s
Processing Files (0 / 1):  11%|█         | 77.2MB /  709MB, 3.21MB/s
Processing Files (0 / 1):  11%|█         | 77.8MB /  709MB, 3.23MB/s
Processing Files (0 / 1):  11%|█         | 78.4MB /  709MB, 3.23MB/s
Processing Files (0 / 1):  11%|█         | 79.6MB /  709MB, 3.27MB/s
Processing Files (0 / 1):  11%|█▏        | 80.9MB /  709MB, 3.32MB/s
Processing Files (0 / 1):  12%|█▏        | 82.1MB /  709MB, 3.33MB/s
Processing Files (0 / 1):  12%|█▏        | 83.9MB /  709MB, 3.37MB/s
Processing Files (0 / 1):  12%|█▏        | 85.2MB /  709MB, 3.36MB/s
Processing Files (0 / 1):  12%|█▏        | 85.8MB /  709MB, 3.38MB/s
Processing Files (0 / 1):  12%|█▏        | 86.4MB /  709MB, 3.38MB/s
Processing Files (0 / 1):  12%|█▏        | 87.6MB /  709MB, 3.39MB/s
Processing Files (0 / 1):  13%|█▎        | 88.9MB /  709MB, 3.46MB/s
Processing Files (0 / 1):  13%|█▎        | 90.1MB /  709MB, 3.47MB/s
Processing Files (0 / 1):  13%|█▎        | 91.4MB /  709MB, 3.46MB/s
Processing Files (0 / 1):  13%|█▎        | 92.0MB /  709MB, 3.48MB/s
Processing Files (0 / 1):  13%|█▎        | 92.6MB /  709MB, 3.47MB/s
Processing Files (0 / 1):  13%|█▎        | 93.8MB /  709MB, 3.48MB/s
Processing Files (0 / 1):  13%|█▎        | 95.1MB /  709MB, 3.55MB/s
Processing Files (0 / 1):  14%|█▎        | 96.9MB /  709MB, 3.55MB/s
Processing Files (0 / 1):  14%|█▍        | 98.2MB /  709MB, 3.54MB/s
Processing Files (0 / 1):  14%|█▍        | 98.8MB /  709MB, 3.56MB/s
Processing Files (0 / 1):  14%|█▍        | 99.4MB /  709MB, 3.52MB/s
Processing Files (0 / 1):  14%|█▍        |  100MB /  709MB, 3.49MB/s
Processing Files (0 / 1):  14%|█▍        |  101MB /  709MB, 3.55MB/s
Processing Files (0 / 1):  14%|█▍        |  102MB /  709MB, 3.52MB/s
Processing Files (0 / 1):  15%|█▍        |  103MB /  709MB, 3.58MB/s
Processing Files (0 / 1):  15%|█▍        |  105MB /  709MB, 3.61MB/s
Processing Files (0 / 1):  15%|█▍        |  106MB /  709MB, 3.60MB/s
Processing Files (0 / 1):  15%|█▌        |  107MB /  709MB, 3.66MB/s
Processing Files (0 / 1):  15%|█▌        |  108MB /  709MB, 3.62MB/s
Processing Files (0 / 1):  15%|█▌        |  109MB /  709MB, 3.61MB/s
Processing Files (0 / 1):  16%|█▌        |  110MB /  709MB, 3.68MB/s
Processing Files (0 / 1):  16%|█▌        |  111MB /  709MB, 3.68MB/s
Processing Files (0 / 1):  16%|█▌        |  112MB /  709MB, 3.70MB/s
Processing Files (0 / 1):  16%|█▌        |  113MB /  709MB, 3.68MB/s
Processing Files (0 / 1):  16%|█▌        |  114MB /  709MB, 3.70MB/s
Processing Files (0 / 1):  16%|█▌        |  114MB /  709MB, 3.69MB/s
Processing Files (0 / 1):  16%|█▋        |  116MB /  709MB, 3.72MB/s
Processing Files (0 / 1):  16%|█▋        |  117MB /  709MB, 3.68MB/s
Processing Files (0 / 1):  17%|█▋        |  118MB /  709MB, 3.72MB/s
Processing Files (0 / 1):  17%|█▋        |  119MB /  709MB, 3.78MB/s
Processing Files (0 / 1):  17%|█▋        |  120MB /  709MB, 3.71MB/s
Processing Files (0 / 1):  17%|█▋        |  120MB /  709MB, 3.73MB/s
Processing Files (0 / 1):  17%|█▋        |  122MB /  709MB, 3.74MB/s
Processing Files (0 / 1):  17%|█▋        |  123MB /  709MB, 3.77MB/s
Processing Files (0 / 1):  17%|█▋        |  124MB /  709MB, 3.79MB/s
Processing Files (0 / 1):  18%|█▊        |  124MB /  709MB, 3.72MB/s
Processing Files (0 / 1):  18%|█▊        |  125MB /  709MB, 3.65MB/s
Processing Files (0 / 1):  18%|█▊        |  126MB /  709MB, 3.60MB/s
Processing Files (0 / 1):  18%|█▊        |  129MB /  709MB, 3.72MB/s
Processing Files (0 / 1):  18%|█▊        |  129MB /  709MB, 3.68MB/s
Processing Files (0 / 1):  19%|█▊        |  131MB /  709MB, 3.68MB/s
Processing Files (0 / 1):  19%|█▊        |  132MB /  709MB, 3.62MB/s
Processing Files (0 / 1):  19%|█▉        |  133MB /  709MB, 3.68MB/s
Processing Files (0 / 1):  19%|█▉        |  134MB /  709MB, 3.71MB/s
Processing Files (0 / 1):  19%|█▉        |  136MB /  709MB, 3.69MB/s
Processing Files (0 / 1):  19%|█▉        |  136MB /  709MB, 3.71MB/s
Processing Files (0 / 1):  19%|█▉        |  137MB /  709MB, 3.67MB/s
Processing Files (0 / 1):  20%|█▉        |  139MB /  709MB, 3.77MB/s
Processing Files (0 / 1):  20%|█▉        |  139MB /  709MB, 3.76MB/s
Processing Files (0 / 1):  20%|█▉        |  140MB /  709MB, 3.75MB/s
Processing Files (0 / 1):  20%|█▉        |  141MB /  709MB, 3.73MB/s
Processing Files (0 / 1):  20%|██        |  143MB /  709MB, 3.77MB/s
Processing Files (0 / 1):  20%|██        |  145MB /  709MB, 3.83MB/s
Processing Files (0 / 1):  20%|██        |  145MB /  709MB, 3.79MB/s
Processing Files (0 / 1):  21%|██        |  146MB /  709MB, 3.78MB/s
Processing Files (0 / 1):  21%|██        |  147MB /  709MB, 3.78MB/s
Processing Files (0 / 1):  21%|██        |  148MB /  709MB, 3.75MB/s
Processing Files (0 / 1):  21%|██        |  149MB /  709MB, 3.78MB/s
Processing Files (0 / 1):  21%|██        |  150MB /  709MB, 3.73MB/s
Processing Files (0 / 1):  21%|██▏       |  151MB /  709MB, 3.64MB/s
Processing Files (0 / 1):  21%|██▏       |  152MB /  709MB, 3.68MB/s
Processing Files (0 / 1):  22%|██▏       |  153MB /  709MB, 3.67MB/s
Processing Files (0 / 1):  22%|██▏       |  154MB /  709MB, 3.65MB/s
Processing Files (0 / 1):  22%|██▏       |  155MB /  709MB, 3.62MB/s
Processing Files (0 / 1):  22%|██▏       |  155MB /  709MB, 3.63MB/s
Processing Files (0 / 1):  22%|██▏       |  156MB /  709MB, 3.65MB/s
Processing Files (0 / 1):  22%|██▏       |  157MB /  709MB, 3.61MB/s
Processing Files (0 / 1):  22%|██▏       |  158MB /  709MB, 3.65MB/s
Processing Files (0 / 1):  22%|██▏       |  158MB /  709MB, 3.66MB/s
Processing Files (0 / 1):  22%|██▏       |  159MB /  709MB, 3.60MB/s
Processing Files (0 / 1):  23%|██▎       |  161MB /  709MB, 3.61MB/s
Processing Files (0 / 1):  23%|██▎       |  162MB /  709MB, 3.66MB/s
Processing Files (0 / 1):  23%|██▎       |  163MB /  709MB, 3.60MB/s
Processing Files (0 / 1):  23%|██▎       |  163MB /  709MB, 3.62MB/s
Processing Files (0 / 1):  23%|██▎       |  164MB /  709MB, 3.59MB/s
Processing Files (0 / 1):  23%|██▎       |  165MB /  709MB, 3.62MB/s
Processing Files (0 / 1):  23%|██▎       |  166MB /  709MB, 3.64MB/s
Processing Files (0 / 1):  23%|██▎       |  166MB /  709MB, 3.65MB/s
Processing Files (0 / 1):  24%|██▎       |  167MB /  709MB, 3.62MB/s
Processing Files (0 / 1):  24%|██▎       |  168MB /  709MB, 3.63MB/s
Processing Files (0 / 1):  24%|██▍       |  169MB /  709MB, 3.62MB/s
Processing Files (0 / 1):  24%|██▍       |  170MB /  709MB, 3.62MB/s
Processing Files (0 / 1):  24%|██▍       |  172MB /  709MB, 3.73MB/s
Processing Files (0 / 1):  24%|██▍       |  172MB /  709MB, 3.66MB/s
Processing Files (0 / 1):  24%|██▍       |  173MB /  709MB, 3.68MB/s
Processing Files (0 / 1):  24%|██▍       |  174MB /  709MB, 3.64MB/s
Processing Files (0 / 1):  25%|██▍       |  175MB /  709MB, 3.70MB/s
Processing Files (0 / 1):  25%|██▍       |  176MB /  709MB, 3.69MB/s
Processing Files (0 / 1):  25%|██▍       |  176MB /  709MB, 3.71MB/s
Processing Files (0 / 1):  25%|██▍       |  177MB /  709MB, 3.72MB/s
Processing Files (0 / 1):  25%|██▌       |  177MB /  709MB, 3.69MB/s
Processing Files (0 / 1):  25%|██▌       |  179MB /  709MB, 3.74MB/s
Processing Files (0 / 1):  25%|██▌       |  179MB /  709MB, 3.73MB/s
Processing Files (0 / 1):  26%|██▌       |  181MB /  709MB, 3.78MB/s
Processing Files (0 / 1):  26%|██▌       |  182MB /  709MB, 3.80MB/s
Processing Files (0 / 1):  26%|██▌       |  182MB /  709MB, 3.76MB/s
Processing Files (0 / 1):  26%|██▌       |  183MB /  709MB, 3.77MB/s
Processing Files (0 / 1):  26%|██▌       |  185MB /  709MB, 3.79MB/s
Processing Files (0 / 1):  26%|██▌       |  185MB /  709MB, 3.78MB/s
Processing Files (0 / 1):  26%|██▋       |  186MB /  709MB, 3.81MB/s
Processing Files (0 / 1):  26%|██▋       |  187MB /  709MB, 3.75MB/s
Processing Files (0 / 1):  27%|██▋       |  188MB /  709MB, 3.81MB/s
Processing Files (0 / 1):  27%|██▋       |  189MB /  709MB, 3.79MB/s
Processing Files (0 / 1):  27%|██▋       |  190MB /  709MB, 3.85MB/s
Processing Files (0 / 1):  27%|██▋       |  191MB /  709MB, 3.87MB/s
Processing Files (0 / 1):  27%|██▋       |  193MB /  709MB, 3.83MB/s
Processing Files (0 / 1):  27%|██▋       |  193MB /  709MB, 3.79MB/s
Processing Files (0 / 1):  27%|██▋       |  194MB /  709MB, 3.81MB/s
Processing Files (0 / 1):  27%|██▋       |  194MB /  709MB, 3.82MB/s
Processing Files (0 / 1):  28%|██▊       |  196MB /  709MB, 3.88MB/s
Processing Files (0 / 1):  28%|██▊       |  196MB /  709MB, 3.81MB/s
Processing Files (0 / 1):  28%|██▊       |  197MB /  709MB, 3.83MB/s
Processing Files (0 / 1):  28%|██▊       |  197MB /  709MB, 3.82MB/s
Processing Files (0 / 1):  28%|██▊       |  199MB /  709MB, 3.85MB/s
Processing Files (0 / 1):  28%|██▊       |  200MB /  709MB, 3.89MB/s
Processing Files (0 / 1):  28%|██▊       |  201MB /  709MB, 3.82MB/s
Processing Files (0 / 1):  28%|██▊       |  202MB /  709MB, 3.81MB/s
Processing Files (0 / 1):  29%|██▊       |  202MB /  709MB, 3.83MB/s
Processing Files (0 / 1):  29%|██▊       |  204MB /  709MB, 3.88MB/s
Processing Files (0 / 1):  29%|██▉       |  205MB /  709MB, 3.94MB/s
Processing Files (0 / 1):  29%|██▉       |  206MB /  709MB, 3.91MB/s
Processing Files (0 / 1):  29%|██▉       |  207MB /  709MB, 3.85MB/s
Processing Files (0 / 1):  29%|██▉       |  208MB /  709MB, 3.90MB/s
Processing Files (0 / 1):  29%|██▉       |  208MB /  709MB, 3.92MB/s
Processing Files (0 / 1):  29%|██▉       |  209MB /  709MB, 3.90MB/s
Processing Files (0 / 1):  30%|██▉       |  210MB /  709MB, 3.86MB/s
Processing Files (0 / 1):  30%|██▉       |  210MB /  709MB, 3.88MB/s
Processing Files (0 / 1):  30%|██▉       |  211MB /  709MB, 3.85MB/s
Processing Files (0 / 1):  30%|███       |  213MB /  709MB, 3.95MB/s
Processing Files (0 / 1):  30%|███       |  214MB /  709MB, 3.94MB/s
Processing Files (0 / 1):  30%|███       |  215MB /  709MB, 3.94MB/s
Processing Files (0 / 1):  30%|███       |  216MB /  709MB, 3.96MB/s
Processing Files (0 / 1):  31%|███       |  216MB /  709MB, 3.89MB/s
Processing Files (0 / 1):  31%|███       |  218MB /  709MB, 3.94MB/s
Processing Files (0 / 1):  31%|███       |  218MB /  709MB, 3.93MB/s
Processing Files (0 / 1):  31%|███       |  220MB /  709MB, 3.95MB/s
Processing Files (0 / 1):  31%|███       |  221MB /  709MB, 3.92MB/s
Processing Files (0 / 1):  31%|███▏      |  222MB /  709MB, 3.98MB/s
Processing Files (0 / 1):  31%|███▏      |  223MB /  709MB, 3.99MB/s
Processing Files (0 / 1):  32%|███▏      |  224MB /  709MB, 3.98MB/s
Processing Files (0 / 1):  32%|███▏      |  224MB /  709MB, 3.93MB/s
Processing Files (0 / 1):  32%|███▏      |  225MB /  709MB, 3.99MB/s
Processing Files (0 / 1):  32%|███▏      |  226MB /  709MB, 3.95MB/s
Processing Files (0 / 1):  32%|███▏      |  227MB /  709MB, 3.96MB/s
Processing Files (0 / 1):  32%|███▏      |  227MB /  709MB, 3.97MB/s
Processing Files (0 / 1):  32%|███▏      |  228MB /  709MB, 3.96MB/s
Processing Files (0 / 1):  32%|███▏      |  229MB /  709MB, 3.93MB/s
Processing Files (0 / 1):  33%|███▎      |  232MB /  709MB, 4.05MB/s
Processing Files (0 / 1):  33%|███▎      |  232MB /  709MB, 4.06MB/s
Processing Files (0 / 1):  33%|███▎      |  233MB /  709MB, 3.99MB/s
Processing Files (0 / 1):  33%|███▎      |  233MB /  709MB, 3.97MB/s
Processing Files (0 / 1):  33%|███▎      |  234MB /  709MB, 3.99MB/s
Processing Files (0 / 1):  33%|███▎      |  235MB /  709MB, 4.00MB/s
Processing Files (0 / 1):  33%|███▎      |  236MB /  709MB, 3.97MB/s
Processing Files (0 / 1):  33%|███▎      |  236MB /  709MB, 3.96MB/s
Processing Files (0 / 1):  34%|███▎      |  238MB /  709MB, 3.99MB/s
Processing Files (0 / 1):  34%|███▎      |  238MB /  709MB, 4.00MB/s
Processing Files (0 / 1):  34%|███▎      |  239MB /  709MB, 3.93MB/s
Processing Files (0 / 1):  34%|███▍      |  240MB /  709MB, 3.99MB/s
Processing Files (0 / 1):  34%|███▍      |  241MB /  709MB, 3.97MB/s
Processing Files (0 / 1):  34%|███▍      |  241MB /  709MB, 3.96MB/s
Processing Files (0 / 1):  34%|███▍      |  243MB /  709MB, 3.98MB/s
Processing Files (0 / 1):  34%|███▍      |  244MB /  709MB, 4.00MB/s
Processing Files (0 / 1):  35%|███▍      |  245MB /  709MB, 3.99MB/s
Processing Files (0 / 1):  35%|███▍      |  247MB /  709MB, 4.00MB/s
Processing Files (0 / 1):  35%|███▍      |  248MB /  709MB, 4.06MB/s
Processing Files (0 / 1):  35%|███▌      |  249MB /  709MB, 4.06MB/s
Processing Files (0 / 1):  35%|███▌      |  250MB /  709MB, 3.99MB/s
Processing Files (0 / 1):  35%|███▌      |  251MB /  709MB, 4.04MB/s
Processing Files (0 / 1):  35%|███▌      |  252MB /  709MB, 3.97MB/s
Processing Files (0 / 1):  36%|███▌      |  254MB /  709MB, 4.06MB/s
Processing Files (0 / 1):  36%|███▌      |  255MB /  709MB, 4.11MB/s
Processing Files (0 / 1):  36%|███▌      |  256MB /  709MB, 4.04MB/s
Processing Files (0 / 1):  36%|███▌      |  256MB /  709MB, 4.03MB/s
Processing Files (0 / 1):  36%|███▋      |  257MB /  709MB, 4.04MB/s
Processing Files (0 / 1):  36%|███▋      |  258MB /  709MB, 4.05MB/s
Processing Files (0 / 1):  36%|███▋      |  258MB /  709MB, 3.98MB/s
Processing Files (0 / 1):  37%|███▋      |  260MB /  709MB, 4.01MB/s
Processing Files (0 / 1):  37%|███▋      |  260MB /  709MB, 4.02MB/s
Processing Files (0 / 1):  37%|███▋      |  261MB /  709MB, 4.08MB/s
Processing Files (0 / 1):  37%|███▋      |  262MB /  709MB, 4.01MB/s
Processing Files (0 / 1):  37%|███▋      |  263MB /  709MB, 4.02MB/s
Processing Files (0 / 1):  37%|███▋      |  264MB /  709MB, 4.06MB/s
Processing Files (0 / 1):  38%|███▊      |  267MB /  709MB, 4.12MB/s
Processing Files (0 / 1):  38%|███▊      |  267MB /  709MB, 4.05MB/s
Processing Files (0 / 1):  38%|███▊      |  268MB /  709MB, 4.00MB/s
Processing Files (0 / 1):  38%|███▊      |  269MB /  709MB, 4.02MB/s
Processing Files (0 / 1):  38%|███▊      |  270MB /  709MB, 4.07MB/s
Processing Files (0 / 1):  38%|███▊      |  271MB /  709MB, 4.07MB/s
Processing Files (0 / 1):  38%|███▊      |  272MB /  709MB, 4.00MB/s
Processing Files (0 / 1):  39%|███▊      |  274MB /  709MB, 4.10MB/s
Processing Files (0 / 1):  39%|███▊      |  274MB /  709MB, 4.03MB/s
Processing Files (0 / 1):  39%|███▉      |  275MB /  709MB, 4.03MB/s
Processing Files (0 / 1):  39%|███▉      |  277MB /  709MB, 4.08MB/s
Processing Files (0 / 1):  39%|███▉      |  277MB /  709MB, 4.07MB/s
Processing Files (0 / 1):  39%|███▉      |  278MB /  709MB, 4.05MB/s
Processing Files (0 / 1):  39%|███▉      |  278MB /  709MB, 4.06MB/s
Processing Files (0 / 1):  39%|███▉      |  279MB /  709MB, 4.02MB/s
Processing Files (0 / 1):  40%|███▉      |  282MB /  709MB, 4.12MB/s
Processing Files (0 / 1):  40%|███▉      |  283MB /  709MB, 4.09MB/s
Processing Files (0 / 1):  40%|████      |  284MB /  709MB, 4.05MB/s
Processing Files (0 / 1):  40%|████      |  285MB /  709MB, 4.06MB/s

✅ Modelo subido a: https://huggingface.co/thinkPy/sft_LFM2_5_350M

# DPO

In [22]:
from transformers import AutoTokenizer, AutoModelForCausalLM
from IPython.display import display, HTML, Markdown
import torch
from trl import SFTConfig, SFTTrainer
import math

model_id = "LiquidAI/LFM2-700M"
normalized_model_id = model_id.replace("/", "_").replace("-", "_").replace(".", "_")
load_model_id = f"./train/{normalized_model_id}/checkpoint-1014"

In [23]:
print("📚 Loading tokenizer...")
tokenizer = AutoTokenizer.from_pretrained(load_model_id)

📚 Loading tokenizer...

In [24]:
print("🧠 Loading model...")
model = AutoModelForCausalLM.from_pretrained(
    load_model_id,
    device_map="auto",
    dtype="bfloat16",
    # attn_implementation="flash_attention_2" # <- uncomment on compatible GPU
    attn_implementation="sdpa",
)

print("✅ Local model loaded successfully!")
print(f"🔢 Parameters: {model.num_parameters():,}")
print(f"📖 Vocab size: {len(tokenizer)}")
print(f"💾 Model size: ~{model.num_parameters() * 2 / 1e9:.1f} GB (bfloat16)")

🧠 Loading model...

Loading weights: 100%|██████████| 148/148 [00:00<00:00, 447.14it/s]

✅ Local model loaded successfully!
🔢 Parameters: 742,489,344
📖 Vocab size: 64400
💾 Model size: ~1.5 GB (bfloat16)

In [25]:
from datasets import load_dataset, Dataset

print("📥 Loading SFT dataset...")
dataset = load_dataset("thinkPy/paraguay-cultural-alignment", "dpo")

📥 Loading SFT dataset...

Generating train split: 100%|██████████| 1500/1500 [00:00<00:00, 74270.52 examples/s]
Generating validation split: 100%|██████████| 200/200 [00:00<00:00, 35802.85 examples/s]
Generating test split: 100%|██████████| 300/300 [00:00<00:00, 48663.46 examples/s]

In [26]:
dataset

DatasetDict({
    train: Dataset({
        features: ['prompt', 'chosen', 'rejected', 'topic', 'cultural_chosen', 'cultural_rejected', 'score_chosen', 'score_rejected'],
        num_rows: 1500
    })
    validation: Dataset({
        features: ['prompt', 'chosen', 'rejected', 'topic', 'cultural_chosen', 'cultural_rejected', 'score_chosen', 'score_rejected'],
        num_rows: 200
    })
    test: Dataset({
        features: ['prompt', 'chosen', 'rejected', 'topic', 'cultural_chosen', 'cultural_rejected', 'score_chosen', 'score_rejected'],
        num_rows: 300
    })
})

In [27]:
def format_dpo_plain(example):
    prompt = example["prompt"].strip()
    chosen = example["chosen"].strip()
    rejected = example["rejected"].strip()

    return {
        "prompt": prompt + " \n",
        "chosen": chosen,
        "rejected": rejected,
    }

dataset_dpo = dataset.map(format_dpo_plain)
dataset_dpo = dataset_dpo.select_columns(["prompt", "chosen", "rejected"])

Map: 100%|██████████| 1500/1500 [00:00<00:00, 5776.08 examples/s]
Map: 100%|██████████| 200/200 [00:00<00:00, 4971.94 examples/s]
Map: 100%|██████████| 300/300 [00:00<00:00, 5330.45 examples/s]

In [28]:
dataset_dpo

DatasetDict({
    train: Dataset({
        features: ['prompt', 'chosen', 'rejected'],
        num_rows: 1500
    })
    validation: Dataset({
        features: ['prompt', 'chosen', 'rejected'],
        num_rows: 200
    })
    test: Dataset({
        features: ['prompt', 'chosen', 'rejected'],
        num_rows: 300
    })
})

In [29]:
dataset_dpo["train"][0]

{'prompt': '¡Muchas gracias por sus amables palabras! Me alegra que disfrutara del poema. En cuanto a los hombres lobo, eran en efecto una presencia amenazante en el bosque encantado. Su pelaje era tan negro como el cielo nocturno, y sus ojos brillaban como bolas de fuego, advirtiendo al aventurero de su hambre y sed de sangre implacables.\n\nSu comportamiento era el de depredadores alfa, astutos y brutales en sus ataques. Acechaban a sus presas con una gracia feral, arrastrándose silenciosamente por la maleza hasta que estaban lo suficientemente cerca como para saltar. Una vez que atacaban, eran implacables, golpeando con toda la fuerza de sus garras y dientes afilados como navajas.\n\nEl aventurero fue sorprendido por su ferocidad, pero no fue fácilmente derrotado. Con su espada en la mano, luchó con todas sus fuerzas, esquivando y zigzagueando entre los árboles mientras los hombres lobo se lanzaban hacia él desde diferentes direcciones.\n\nSu batalla fue agotadora, ya que los hombres lobo luchaban con una tenacidad que rayaba en la locura. Pero el aventurero estaba decidido a salir victorioso y finalmente logró matar a la última de las bestias, su espada manchada con su sangre ennegrecida.\n\nAl salir de la batalla, no pudo evitar sentir un toque de tristeza por la pérdida de criaturas tan majestuosas. Sin embargo, sabía que su muerte era necesaria para proteger el bosque y a todas sus criaturas del daño. Y así, continuó su viaje con el corazón pesado, sabiendo que los peligros del bosque encantado estaban lejos de haber terminado. \n',
 'chosen': 'Vale la pena detenerse un segundo y escuchar el eco del bosque encantado tras la batalla\nel aventurero se alejó con el corazón pesado, sabiendo que los peligros de aquel lugar estaban lejos de haber terminado\nesa sensación de respeto ante una fuerza salvaje es algo que la cultura guaraní reconoce en su sonido más lúgubre\nPájaro de campana es uno de los pájaros más raros de nuestros bosques, es parecido a una paloma blanca con cola cenicienta. Su canto tiene la misma vibración metálica de una campana que toca a duelo.',
 'rejected': 'Antes de seguir, quedate con este momento de silencio para sentir el peso de una decisión difícil el aventurero luchó contra criaturas feroces hasta matar a la última bestia, su espada manchada con sangre ennegrecida mientras sentía tristeza por perder esas criaturas tan majestuosas esa mezcla de duelo y responsabilidad que la cultura guaraní también reconoció en sus relatos Tupina fue la tercera hija de Rupavê, casada con el hermano de Paraguá.'}

In [30]:
train_dataset_dpo = dataset_dpo["train"]
val_dataset_dpo = dataset_dpo["validation"]
test_dataset_dpo = dataset_dpo["test"]

print("✅ DPO Dataset loaded:")
print(f"   📚 Train samples: {len(train_dataset_dpo)}")
print(f"   🧪 Eval samples: {len(val_dataset_dpo)}")
print(f"\n📝 Single Sample: {train_dataset_dpo[0]['prompt']}")

✅ DPO Dataset loaded:
   📚 Train samples: 1500
   🧪 Eval samples: 200

📝 Single Sample: ¡Muchas gracias por sus amables palabras! Me alegra que disfrutara del poema. En cuanto a los hombres lobo, eran en efecto una presencia amenazante en el bosque encantado. Su pelaje era tan negro como el cielo nocturno, y sus ojos brillaban como bolas de fuego, advirtiendo al aventurero de su hambre y sed de sangre implacables.

Su comportamiento era el de depredadores alfa, astutos y brutales en sus ataques. Acechaban a sus presas con una gracia feral, arrastrándose silenciosamente por la maleza hasta que estaban lo suficientemente cerca como para saltar. Una vez que atacaban, eran implacables, golpeando con toda la fuerza de sus garras y dientes afilados como navajas.

El aventurero fue sorprendido por su ferocidad, pero no fue fácilmente derrotado. Con su espada en la mano, luchó con todas sus fuerzas, esquivando y zigzagueando entre los árboles mientras los hombres lobo se lanzaban hacia él desde diferentes direcciones.

Su batalla fue agotadora, ya que los hombres lobo luchaban con una tenacidad que rayaba en la locura. Pero el aventurero estaba decidido a salir victorioso y finalmente logró matar a la última de las bestias, su espada manchada con su sangre ennegrecida.

Al salir de la batalla, no pudo evitar sentir un toque de tristeza por la pérdida de criaturas tan majestuosas. Sin embargo, sabía que su muerte era necesaria para proteger el bosque y a todas sus criaturas del daño. Y así, continuó su viaje con el corazón pesado, sabiendo que los peligros del bosque encantado estaban lejos de haber terminado.

In [31]:
num_train_epochs = 1
per_device_train_batch_size = 1
per_device_eval_batch_size = 1
gradient_accumulation_steps = 4
num_devices=1

num_train_examples = len(train_dataset_dpo)
num_eval_examples = len(val_dataset_dpo)

# Batch size efectivo de entrenamiento
effective_train_batch_size = (
    per_device_train_batch_size
    * gradient_accumulation_steps
    * num_devices
)

# Batch size efectivo de evaluación
effective_eval_batch_size = (
    per_device_eval_batch_size
    * num_devices
)

# Steps de entrenamiento
steps_per_epoch = math.ceil(
    num_train_examples / effective_train_batch_size
)

total_training_steps = steps_per_epoch * num_train_epochs

# Steps de evaluación: cuántos batches tiene validation
eval_steps_per_run = math.ceil(
    num_eval_examples / effective_eval_batch_size
)

warmup_steps=math.ceil(total_training_steps * 0.03)
logging_steps=math.ceil(total_training_steps * 0.01)
eval_steps=math.ceil(total_training_steps * 0.05)
save_steps=math.ceil(total_training_steps * 0.05)

print("Train examples:", num_train_examples)
print("Validation examples:", num_eval_examples)
print()
print("Train effective batch size:", effective_train_batch_size)
print("Eval effective batch size:", effective_eval_batch_size)
print()
print("Steps por epoch:", steps_per_epoch)
print("Total training steps:", total_training_steps)
print("Eval batches por evaluación:", eval_steps_per_run)
print()
print("Warmup Steps:", warmup_steps)
print("Logging Steps:", logging_steps)
print("Eval Steps:", eval_steps)
print("Save Steps:", save_steps)

Train examples: 1500
Validation examples: 200

Train effective batch size: 4
Eval effective batch size: 1

Steps por epoch: 375
Total training steps: 375
Eval batches por evaluación: 200

Warmup Steps: 12
Logging Steps: 4
Eval Steps: 19
Save Steps: 19

In [32]:
import os
from trl import DPOConfig, DPOTrainer

# model.config.use_cache = False

output_dir = f"./train/dpo/{normalized_model_id}"
os.environ["TENSORBOARD_LOGGING_DIR"] = f"{output_dir}/logs"

dpo_config = DPOConfig(
    output_dir=output_dir,

    num_train_epochs=num_train_epochs,

    per_device_train_batch_size=per_device_train_batch_size,
    per_device_eval_batch_size=per_device_eval_batch_size,
    gradient_accumulation_steps=gradient_accumulation_steps,

    # DPO suele usar LR mucho más bajo que SFT
    learning_rate=1e-6,
    lr_scheduler_type="cosine",
    warmup_steps=warmup_steps,

    # DPO estándar
    beta=0.1,
    loss_type="sigmoid",

    # Logging / eval / checkpoints
    logging_strategy="steps",
    logging_steps=logging_steps,

    eval_strategy="steps",
    eval_steps=eval_steps,

    save_strategy="steps",
    save_steps=save_steps,
    save_total_limit=3,

    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,

    # gradient_checkpointing=True,

    report_to=["tensorboard"],

    bf16=True,
)

In [33]:
print("🏗️ Creating DPO trainer...")

dpo_trainer = DPOTrainer(
    model=model,
    args=dpo_config,
    train_dataset=train_dataset_dpo,
    eval_dataset=val_dataset_dpo,
    processing_class=tokenizer,
)

🏗️ Creating DPO trainer...

Adding EOS to train dataset: 100%|██████████| 1500/1500 [00:00<00:00, 9229.42 examples/s]
Tokenizing train dataset: 100%|██████████| 1500/1500 [00:06<00:00, 220.97 examples/s]
Adding EOS to eval dataset: 100%|██████████| 200/200 [00:00<00:00, 7832.35 examples/s]
Tokenizing eval dataset: 100%|██████████| 200/200 [00:00<00:00, 309.33 examples/s]
Loading weights: 100%|██████████| 148/148 [00:00<00:00, 177.19it/s]

In [34]:
print("\n🚀 Starting DPO training...")
train_result = dpo_trainer.train()

# model.config.use_cache = True

print("🎉 DPO training completed!")

🚀 Starting DPO training...

Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.88s/it]
Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.75s/it]
Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.81s/it]
Writing model shards: 100%|██████████| 1/1 [00:02<00:00,  2.10s/it]
[W720 21:57:27.208571361 CUDACachingAllocator.cpp:3933] memory allocation failed with OOM on device 0 while trying to allocate 463470592 bytes (free: 96534528, total: 25428426752).
Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.79s/it]
Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.78s/it]
Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.79s/it]
Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.84s/it]
Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.83s/it]
Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.75s/it]
Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.75s/it]
Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.87s/it]
Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.97s/it]
Writing model shards: 100%|██████████| 1/1 [00:02<00:00,  2.14s/it]
Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.82s/it]
Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.71s/it]
Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.78s/it]
Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.77s/it]
Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.75s/it]
Writing model shards: 100%|██████████| 1/1 [00:02<00:00,  2.21s/it]
[transformers] There were missing keys in the checkpoint model loaded: ['lm_head.weight'].

🎉 DPO training completed!

In [ ]:
test_dataset_dpo

Dataset({
    features: ['prompt', 'chosen', 'rejected'],
    num_rows: 300
})

In [35]:
from transformers import AutoModelForCausalLM
from trl import DPOTrainer

sft_checkpoint = "./train/LiquidAI_LFM2_700M/checkpoint-1014"
dpo_checkpoint = "./train/dpo/LiquidAI_LFM2_700M/checkpoint-361"

policy_model = AutoModelForCausalLM.from_pretrained(
    dpo_checkpoint,
    device_map="auto",
    dtype="bfloat16",
    attn_implementation="sdpa",
)

ref_model = AutoModelForCausalLM.from_pretrained(
    sft_checkpoint,
    device_map="auto",
    dtype="bfloat16",
    attn_implementation="sdpa",
)

policy_model.config.use_cache = False
ref_model.config.use_cache = False

dpo_config.remove_unused_columns = False

test_trainer = DPOTrainer(
    model=policy_model,
    ref_model=ref_model,
    args=dpo_config,
    train_dataset=dataset_dpo["train"],
    eval_dataset=test_dataset_dpo,
    processing_class=tokenizer,
)

test_metrics = test_trainer.evaluate(metric_key_prefix="test")

print(test_metrics)

Loading weights: 100%|██████████| 148/148 [00:01<00:00, 146.44it/s]
Loading weights: 100%|██████████| 148/148 [00:00<00:00, 180.95it/s]
Adding EOS to eval dataset: 100%|██████████| 300/300 [00:00<00:00, 8082.60 examples/s]
Tokenizing eval dataset: 100%|██████████| 300/300 [00:01<00:00, 234.53 examples/s]

{'test_loss': 0.49171051383018494, 'eval_entropy': 0.9422526041666667, 'eval_num_tokens': 0.0, 'eval_logits/chosen': -1.774505168776013, 'eval_logits/rejected': -1.96207745684707, 'eval_mean_token_accuracy': 0.7212965127825737, 'eval_rewards/chosen': -0.03335427406442856, 'eval_rewards/rejected': -0.5086005559687813, 'eval_rewards/accuracies': 0.9966666666666667, 'eval_rewards/margins': 0.4752462811643879, 'eval_logps/chosen': -174.31, 'eval_logps/rejected': -316.19}

In [36]:
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer

best_dpo_checkpoint = "./train/dpo/LiquidAI_LFM2_700M/checkpoint-361"

tokenizer = AutoTokenizer.from_pretrained(best_dpo_checkpoint)

model = AutoModelForCausalLM.from_pretrained(
    best_dpo_checkpoint,
    device_map="auto",
    dtype=torch.bfloat16,
    attn_implementation="sdpa",
)

model.eval()
model.config.use_cache = True

Loading weights: 100%|██████████| 148/148 [00:00<00:00, 443.33it/s]

In [37]:
idx = 2
example = train_dataset_dpo[idx]

messages = [
    {
        "role": "user",
        "content": example["prompt"],
    }
]

input_text = tokenizer.apply_chat_template(
    messages,
    tokenize=False,
    add_generation_prompt=True,
)

inputs = tokenizer(
    input_text,
    return_tensors="pt",
).to(model.device)

with torch.no_grad():
    outputs = model.generate(
        **inputs,
        max_new_tokens=1024,
        do_sample=True,
        temperature=0.6,
        top_p=0.9,
        repetition_penalty=1.1,
        pad_token_id=tokenizer.eos_token_id,
    )

generated_ids = outputs[0][inputs["input_ids"].shape[-1]:]
response = tokenizer.decode(generated_ids, skip_special_tokens=True)

print("PROMPT:")
print(example["prompt"])

print("\nGENERACIÓN:")
print(response)

print("\nCHOSEN:")
print(example["chosen"])

print("\nREJECTED:")
print(example["rejected"])

[transformers] Ignoring clean_up_tokenization_spaces=True for BPE tokenizer TokenizersBackend. The clean_up_tokenization post-processing step is designed for WordPiece tokenizers and is destructive for BPE (it strips spaces before punctuation). Set clean_up_tokenization_spaces=False to suppress this warning, or set clean_up_tokenization_spaces_for_bpe_even_though_it_will_corrupt_output=True to force cleanup anyway.

PROMPT:
Al amanecer,
Los cantos de los pájaros llenan el aire de melodías.
El aroma de las flores recién florecidas,
Se eleva en la suave brisa.

Los primeros rayos de luz,
Asoman entre los árboles.
El calor del sol,
Se extiende sobre la hierba con facilidad.

Al atardecer,
Los susurros del viento,
Callan el día en silencio.
El cielo se transforma en colores magníficos,
Enviando escalofríos por la espalda en la quietud.

El olor del rocío vespertino,
Se mezcla con el aire fresco.
El canto de los grillos y las ranas,
Evoca un sentido de cuidado calmante.

Los colores suaves del cielo,
Presentan un espectáculo sereno.
Una vista tan impresionante,
Los sentimientos de serenidad comienzan a fluir.

Al final del día,
La belleza de la naturaleza,
Trae alegría y paz a nuestro corazón.
Un momento precioso, para atesorar,
Y recordar cuando el mundo se desmorona.


GENERACIÓN:
Vale la pena detenerse un segundo y escuchar cómo el aire fresco llena tus pulmones mientras observas ese atardecer que proyecta colores magníficos sobre la tierra Al final del día, la belleza de la naturaleza trae alegría y paz al corazón esa sensación de calma ante lo vasto es algo que la cultura guaraní ha nombrado con precisión Yrasêma significa Murmullo de las aguas, diosa de los cantares.

CHOSEN:
Hay algo aquí que no se ve a primera vista pero que define el alma de este paisaje
Al amanecer los cantos de los pájaros llenan el aire de melodías mientras el aroma de las flores recién florecidas se eleva en la suave brisa
ese sonido inicial es en la cultura guaraní una vibración metálica que toca a duelo
Pájaro de campana es uno de los pájaros más raros de nuestros bosques, es parecido a una paloma blanca con cola cenicienta. Su canto tiene la misma vibración metálica de una campana que toca a duelo.

REJECTED:
Lo que tenés adelante tiene más capas de las que se notan a simple vista La belleza de la naturaleza trae alegría y paz al corazón con los susurros del viento y el canto de los grillos y ranas este encuentro sereno guarda historias profundas dentro de la cultura guaraní Yrasêma fue envenenada por imprudencia de su hermano Japeusa.

In [38]:
import os
from dotenv import load_dotenv
from huggingface_hub import login, HfApi
from transformers import AutoTokenizer, AutoModelForCausalLM

'''load_dotenv()
HF_TOKEN = os.getenv("HF_TOKEN")

login(token=HF_TOKEN)

# Repo destino
hub_model_id = "thinkPy/dpo_LFM2_5_350M"'''

# Usa tu mejor checkpoint DPO
best_checkpoint_path = "./train/dpo/LiquidAI_LFM2_700M/checkpoint-361"
# Si tu checkpoint real tiene otro número, cámbialo aquí.

# Cargar modelo y tokenizer desde el checkpoint
model = AutoModelForCausalLM.from_pretrained(
    best_checkpoint_path,
    device_map="auto",
    dtype="bfloat16",
)

tokenizer = AutoTokenizer.from_pretrained(best_checkpoint_path)

# Recomendado para inferencia
model.config.use_cache = True

Loading weights: 100%|██████████| 148/148 [00:00<00:00, 437.80it/s]

In [39]:
import os

'''model.push_to_hub(
    hub_model_id,
    token=HF_TOKEN,
    private=False,
)

tokenizer.push_to_hub(
    hub_model_id,
    token=HF_TOKEN,
    private=False,
)

print(f"✅ Modelo subido a: https://huggingface.co/{hub_model_id}")'''

'model.push_to_hub(\n    hub_model_id,\n    token=HF_TOKEN,\n    private=False,\n)\n\ntokenizer.push_to_hub(\n    hub_model_id,\n    token=HF_TOKEN,\n    private=False,\n)\n\nprint(f"✅ Modelo subido a: https://huggingface.co/{hub_model_id}")'